### PR TITLE
Algorithms

### PR DESCRIPTION
**Pull request by jeromekelleher**
Here's a draft of the branch stat algorithm. I spent a while working on a version in which we use the ``diffs()`` operator  to simplify the logic a bit, but it ended up being more work to explain how the diffs worked. I like that this is very explicit also --- literally all we need is the tables and the pre-computed I and O indexes.

If you like the general outline of this @petrelharp, please merge and I'll start polishing it and writing some text around it.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I've added a rough outline of a figure I think would be useful @petrelharp (see below). The idea is to show the internal state of the algorithm while we're adding and removing edges. I think this is the best way of making it really concrete how it all works.

What do you think? It's pretty clunky at the moment, so definitely open to ideas on how to improve it!

Screenshot from 2019-09-01 17-47-51

**Comment by petrelharp** [comment]
I'm into it: this figure is useful.

I will merge this tomorrow, as requested?

**Comment by jeromekelleher** [comment]
Great! Maybe showing four states is excessive. We can probably illustrate all the important stuff by showing two states: one with a complete tree and the next where we remove one edge that disconnects a full subtree? This would reduce the "wall of numbers" effect we have here.

**Comment by jeromekelleher** [comment]
I've updated the figure to use two states now @petrelharp. We're good to merge this much I think.

**Pull request merged**
