### PR TITLE
Fix Makefile, which got broken in 13a83279357b0fa5ca146a5f335e5a0a864…

### PR DESCRIPTION
**Pull request by molpopgen**

### CODE REVIEW

**Comment by petrelharp** [comment]
Whoops, sorry. I don't think this works either, though. Fixed upstream.

**Comment by molpopgen** [comment]
What do you mean by "not work"?  That is exactly the Makefile that I used.

**Comment by petrelharp** [comment]
```
peter@skua:~/projects/tskit-dev/treestats_ms/tskit_stat_benchmarks$ git fetch origin pull/15/head:fix_Makefile
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From github.com:petrelharp/treestats_ms
 * [new ref]         refs/pull/15/head -> fix_Makefile
peter@skua:~/projects/tskit-dev/treestats_ms/tskit_stat_benchmarks$ git checkout fix_Makefile 
Switched to branch 'fix_Makefile'
peter@skua:~/projects/tskit-dev/treestats_ms/tskit_stat_benchmarks$ tail Makefile 
	python3 $< > $@

benchmarks_without_copy.txt: benchmarks_no_conversion2.py
	python3 $< > $@

benchmarks_without_copy_longer_genome.txt: benchmarks_no_conversion_longer_genome.py
	python3 $< > $@

benchmarks_without_copy_longer_genome.pdf: benchmarks_without_copy_longer_genome.txt
	python3 $< > $@
peter@skua:~/projects/tskit-dev/treestats_ms/tskit_stat_benchmarks$ touch benchmarks_without_copy_longer_genome.txt && make benchmarks_without_copy_longer_genome.pdf
python3 benchmarks_without_copy_longer_genome.txt > benchmarks_without_copy_longer_genome.pdf
  File "benchmarks_without_copy_longer_genome.txt", line 1
    toolkit nsam nmutations Nu nbytes seconds
               ^
SyntaxError: invalid syntax
make: *** [Makefile:13: benchmarks_without_copy_longer_genome.pdf] Error 1
```

**Comment by molpopgen** [comment]
Yeah, I hadn't seen the entire file.  GitHub only showed the diff, so I thought the target was removed.  I commented on the commit--the Makefile for plots should be separate, as we cannot guarantee time stamps.

**Pull request closed without merging**
